<?php
/**
 * Created by PhpStorm.
 * User: evalor
 * Date: 2019-03-26
 * Time: 19:17
 */

namespace Test\User;

use App\Model\User\UserBean;
use App\Model\User\UserModel;
use EasySwoole\MysqliPool\Mysql;
use Curl\Curl;
use Test\BaseTest;

/**
 * API测试基类
 * Class BaseApiTestCase
 * @package Test\ApiTest
 */
class UserBaseTestCase extends BaseTest
{
    protected $apiBase = 'http://127.0.0.1:9602/Api/User';
    protected $userSession;
    protected $curl;
    protected $modelName = '';

    protected $user = [
        'phone'    => '18959261286',
        'password' => '123456'
    ];

    /**
     * @var $userBean UserModel
     */
    protected $userBean;

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->curl = new Curl();
        $this->register();
        $this->login();
        $this->curlInit();
        $this->getUserInfo();
        $this->LoginError();
    }

    function register()
    {
        //判断会员是否存在
        $model = new UserModel();
        $model->phone = $this->user['phone'];
        $userInfo = $model->getOneByPhone('userId');
        if ($userInfo) {
            $userInfo->update(['userPassword' => md5($this->user['password']), 'isDelete' => 0, 'isForbid' => 0]);

        } else {
            $url = $this->apiBase . '/' . 'Auth' . '/register';
            $curl = $this->curl;
            $time = time();
            $curl->setCookies([
                'smsVerifyCodeHash' => md5('123456' . $time . $this->user['phone'] . 'sms'),
                'smsVerifyCodeTime' => $time,
                'smsVerifyPhone'    => $this->user['phone'],
            ]);
            $data = [
                'smsVerifyCode' => '123456',
                'userPassword'  => $this->user['password'],
            ];
            $curl->get($url, $data);
            if ($curl->response) {
//            var_dump($curl->response);
            } else {
                echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
            }
            $this->assertTrue(!!$curl->response);
            $this->assertEquals(200, $curl->response->code);
        }
    }

    public function curlInit()
    {
        $this->curl->setCookies([
            'userSession' => $this->userSession,
        ]);
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->logout();
//        $this->delete();
    }

    public function getUserInfo()
    {
        $url = $this->apiBase . '/' . 'Auth' . '/getInfo';
        $curl = $this->curl;
        $data = [
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals(200, $curl->response->code);
        $this->userBean = new UserModel((array)$curl->response->result);
    }

    public function login()
    {
        $url = $this->apiBase . '/Auth/login';
        $curl = $this->curl;
        $time = time();
        $curl->setCookies([
            'verifyCodeHash' => md5('1234' . $time),
            'verifyCodeTime' => $time,
        ]);
        $data = [
            'phone'      => $this->user['phone'],
            'password'   => $this->user['password'],
            'verifyCode' => '1234',
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals(200, $curl->response->code);
        $this->userSession = $curl->response->result->userSession;
    }

    public function loginError()
    {
        $url = $this->apiBase . '/Auth/login';
        $curl = $this->curl;
        $time = time();
        $curl->setCookies([
            'verifyCodeHash' => md5('1234' . $time),
            'verifyCodeTime' => $time,
        ]);
        $data = [
            'phone'      => $this->user['phone'],
            'password'   => '1114444',
            'verifyCode' => '1234',
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals(400, $curl->response->code);
        $this->assertEquals('帐号或密码错误', $curl->response->msg);
    }

    public function logout()
    {
        $url = $this->apiBase . '/Auth/logout';
        $curl = $this->curl;
        $data = [
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals(200, $curl->response->code);
    }
}