<?php
/**
 * Created by PhpStorm.
 * User: Tioncico
 * Date: 2019/3/26 0026
 * Time: 17:45
 */

namespace Test\Admin;

use App\Model\Admin\AdminUserModel;

class AdminUserTest extends AdminBaseTestCase
{
    /**
     * @var $userInfo AdminUserModel
     */
    static $userInfo;
    protected $getPkMethod;
    protected $modelName = 'AdminUser';
    protected $primaryKey = 'adminId';
    protected $addParam = [
        'adminName'  => 'admin',
        'adminAccount'     => 'admin12',
        'adminPassword' => '123456',
        'isForbid' => '0',
    ];
    protected $search = [
        'keyword' => 'admin'
    ];
    protected $updateParam = [
        'adminName'             => 'admin12',
        'adminPassword'         => '654321',
    ];

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    function existAccount() {
        $model = new AdminUserModel();
        $model->where(['adminAccount' => $this->addParam['adminAccount']])->update(['isDelete' => 1]);
    }

    /**
     * testAdd
     * @author Tioncico
     * Time: 16:03
     */
    public function testAdd()
    {
        $this->existAccount();
        $url = $this->apiBase . '/'.$this->modelName.'/add';
        $curl = $this->curl;
        $curl->get($url, $this->addParam);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }

    /**
     * testGetAll
     * @author Tioncico
     * Time: 15:49
     */
    public function testGetAll()
    {
        $url = $this->apiBase . '/'.$this->modelName.'/getAll';
        $curl = $this->curl;
        $curl->get($url, $this->search);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
        $this->assertGreaterThan(0, $curl->response->result->total);
        self::$userInfo = new AdminUserModel((array)$curl->response->result->list[0]);
    }

    /**
     * @depends testGetAll
     * testGetOne
     * @author Tioncico
     * Time: 15:50
     */
    public function testGetOne()
    {
        $url = $this->apiBase . '/'.$this->modelName.'/getOne';
        $curl = $this->curl;
        $primaryKey = $this->primaryKey;
        $data = [
            $primaryKey =>  self::$userInfo->$primaryKey,
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }

    /**
     * @depends testGetOne
     * testUpdate
     * @author Tioncico
     * Time: 15:50
     */
    public function testUpdate()
    {
        $url = $this->apiBase . '/'.$this->modelName.'/update';
        $curl = $this->curl;
        $primaryKey = $this->primaryKey;
        $data = [$primaryKey =>  self::$userInfo->$primaryKey] + $this->updateParam;
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }

    /**
     * @depends testUpdate
     * testDelete
     * @author Tioncico
     * Time: 15:50
     */
    public function testDelete()
    {
        $url = $this->apiBase . '/'.$this->modelName.'/delete';
        $curl = $this->curl;
        $primaryKey = $this->primaryKey;
        $data = [
            $primaryKey =>  self::$userInfo->$primaryKey,
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }
}
