<?php
/**
 * Created by PhpStorm.
 * User: evalor
 * Date: 2019-03-26
 * Time: 19:17
 */

namespace Test\Admin;

use App\Model\Admin\AdminUserModel;
use Curl\Curl;
use Test\BaseTest;

/**
 * API测试基类
 * Class BaseApiTestCase
 * @package Test\ApiTest
 */
class AdminBaseTestCase extends BaseTest
{
    protected $apiBase = 'http://127.0.0.1:9602/Api/Admin';
    protected $adminSession;
    protected $curl;
    protected $modelName = '';
    /**
     * @var $adminUser AdminUserModel
     */
    protected $adminUser;

    protected $admin = [
        'account'  => 'admin-user',
        'password' => '123456',
    ];

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->curl = new Curl();
//        $this->register();
        $this->login();
        $this->curlInit();
        $this->getUserInfo();
//        $this->LoginError();
    }

    public function curlInit()
    {
        $this->curl->setCookies([
            'adminSession' => $this->adminSession,
        ]);
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->logout();
    }

    public function getUserInfo()
    {
        $url = $this->apiBase . '/' . 'Auth' . '/getInfo';
        $curl = $this->curl;
        $data = [
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals(200, $curl->response->code);
        $this->adminUser = new AdminUserModel((array)$curl->response->result);
    }

    function existAdmin() {
        $model = new AdminUserModel();
        $model->adminAccount = $this->admin['account'];
        $result = $model->getOneByAccount();

        // 没有这条数据
        if (!$result) {
            $params = [
                'adminName'            => $this->admin['account'],
                'adminAccount'         => $this->admin['account'],
                'adminPassword'        => md5($this->admin['password']),
                'addTime'              => time(),
                'isForbid'             => 0,
                'isDelete'             => 0,
            ];
            $rs = $model::create($params)->save();
            $this->assertTrue(!!$rs);
        } else {
            if ($result->adminPassword === md5($this->admin['password'])) {
                if ($result->isDelete === AdminUserModel::DELETE_TYPE_DELETED) {
                    $ret = $result->update(['isDelete' => 0]);
                    $this->assertTrue(!!$ret);
                }
            } else {
                $rs = $result->update(['adminPassword' => md5($this->admin['password']), 'isForbid' => 0, 'isDelete' => 0]);
                $this->assertTrue($rs !== false);
            }
        }
    }

    public function login()
    {
        $this->existAdmin();

        $url = $this->apiBase . '/Auth/login';
        $curl = $this->curl;
        $time = time();
        $curl->setCookies([
            'verifyCodeHash' => md5('1234' . $time),
            'verifyCodeTime' => $time,
        ]);
        $data = $this->admin + ['verifyCode'   => '1234'];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals(200, $curl->response->code);
        $this->adminSession = $curl->response->result->adminSession;
    }

    public function logout()
    {
        $url = $this->apiBase . '/Auth/logout';
        $curl =$this->curl;
        $data = [
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals(200, $curl->response->code);
    }

}