<?php
/**
 * Created by PhpStorm.
 * User: Tioncico
 * Date: 2019/3/26 0026
 * Time: 17:45
 */

namespace Test\Admin;

use App\Model\Article\ArticleCategoryModel;
use App\Model\Article\ArticleModel;

class ArticleTest extends AdminBaseTestCase
{
    /**
     * @var $info ArticleModel
     */
    static $info;
    /**
     * @var $category ArticleCategoryModel
     */
    static $category;
    protected $modelName = 'Article';
    protected $primaryKey = 'articleId';
    protected $addParam = [
        'title'                 => 'Article测试',
        'description'           => 'Article测试',
        'author'                => 'blank',
        'content'               => 'Article测试',
        'state'                 => 1,
    ];

    protected $search = [
        'keyword'  => 'Article测试',
    ];
    protected $updateParam = [
        'title'                 => 'Article测试12',
        'description'           => 'Article测试12',
        'author'                => 'blank',
        'content'               => 'Article测试12',
        'state'                 => 1,
    ];

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    function existArticleCategory() {
        $model = new ArticleCategoryModel();
        $info = $model->get();
        if (empty($info)) {
            $data = [
                'categoryName'  => '测试',
                'pid'           => 0,
            ];
            $ret = $model::create($data)->save();
            $this->assertTrue(!!$ret);
            $data['categoryId'] = $ret;
            self::$category = $model::create($data);
        } else {
            self::$category = $info;
        }
    }

    /**
     * testAdd
     * @author Tioncico
     * Time: 16:03
     */
    public function testAdd()
    {
        $this->existArticleCategory();
        $url = $this->apiBase . '/'.$this->modelName.'/add';
        $curl = $this->curl;
        $data = $this->addParam + ['categoryId' => self::$category->categoryId];
        var_dump($data);
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }

    /**
     * testGetAll
     * @author Tioncico
     * Time: 15:49
     */
    public function testGetAll()
    {
        $url = $this->apiBase . '/'.$this->modelName.'/getAll';
        $curl = $this->curl;
        $curl->get($url);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
        $this->assertGreaterThan(0, $curl->response->result->total);
        self::$info = new ArticleModel((array) $curl->response->result->list[0]);
    }

    /**
     * @depends testGetAll
     * testGetOne
     * @author Tioncico
     * Time: 15:50
     */
    public function testGetOne()
    {
        $url = $this->apiBase . '/'.$this->modelName.'/getOne';
        $curl = $this->curl;
        $primaryKey = $this->primaryKey;
        $data = [
            $primaryKey =>  self::$info->$primaryKey,
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }

    /**
     * @depends testGetOne
     * testUpdate
     * @author Tioncico
     * Time: 15:50
     */
    public function testUpdate()
    {
        $url = $this->apiBase . '/'.$this->modelName.'/update';
        $curl = $this->curl;
        $primaryKey = $this->primaryKey;
        $data = [$primaryKey =>  self::$info->$primaryKey] + $this->updateParam;
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }

    /**
     * @depends testUpdate
     * testDelete
     * @author Tioncico
     * Time: 15:50
     */
    public function testDelete()
    {
        $url = $this->apiBase . '/'.$this->modelName.'/delete';
        $curl = $this->curl;
        $primaryKey = $this->primaryKey;
        $data = [
            $primaryKey =>  self::$info->$primaryKey,
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }
}
