<?php
/**
 * Created by PhpStorm.
 * User: Tioncico
 * Date: 2019/3/26 0026
 * Time: 16:28
 */

namespace Test\Admin;


class AuthTest extends AdminBaseTestCase
{
    protected $modelName = 'Auth';

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetInfo()
    {
        $url = $this->apiBase . '/' . $this->modelName . '/getInfo';
        $curl = $this->curl;
        $curl->get($url);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals(200, $curl->response->code);
    }
}
