<?php
/**
 * Created by PhpStorm.
 * User: Tioncico
 * Date: 2019/3/26 0026
 * Time: 17:45
 */

namespace Test\Admin;



class UploadFileTest extends AdminBaseTestCase
{
    protected $modelName = 'UploadFile';

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * testFile
     * @author Tioncico
     * Time: 15:50
     */
    public function testFile()
    {
        $url = $this->apiBase . '/' . $this->modelName . '/file';
        $curl = $this->curl;
        $data = [
            'upload'=>new \CURLFile(__FILE__)
        ];
        $curl->post($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success', $curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }
}
