<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 19-8-2
 * Time: 上午10:55
 */

namespace Test\Admin;


use App\Model\User\UserModel;

class UserTest extends AdminBaseTestCase
{
    /**
     * @var $info UserModel
     */
    static $info;
    protected $getPkMethod;
    protected $modelName = 'User';
    protected $primaryKey = 'userId';
    protected $addParam = [
        'userName'            => 'blank',
        'phone'               => '18959261286',
        'sex'                 => 1,
        'userPassword'        => '123456',
        'provinceId'          => 1,
        'cityId'              => 1,
        'countyId'            => 1,
        'address'             => '测试地址',
        'isForbid'            => 0,
    ];
    protected $search = [
        'keyword' => 'blank'
    ];
    protected $updateParam = [
        'userName'            => 'blank12',
        'sex'                 => 1,
        'provinceId'          => 1,
        'cityId'              => 1,
        'countyId'            => 1,
        'address'             => '测试地址12',
        'isForbid'            => 1,
    ];

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    function existPhone() {
        $model = new UserModel();
        $model->where(['phone' => $this->addParam['phone']])->destroy();
    }

    /**
     * testAdd
     * @author Tioncico
     * Time: 16:03
     */
    public function testAdd()
    {
        $this->existPhone();

        $url = $this->apiBase . '/' . $this->modelName . '/add';
        $curl = $this->curl;
        $curl->get($url, $this->addParam);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success', $curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }


    /**
     * testGetAll
     * @author Tioncico
     * Time: 15:49
     */
    public function testGetAll()
    {
        $url = $this->apiBase . '/' . $this->modelName . '/getAll';
        $curl = $this->curl;
        $curl->get($url, $this->search);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success', $curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
        $this->assertGreaterThan(0, $curl->response->result->total);
        self::$info = new UserModel((array)$curl->response->result->list[0]);
    }

    /**
     * @depends testGetAll
     * testGetOne
     * @author Tioncico
     * Time: 15:50
     */
    public function testGetOne()
    {
        $url = $this->apiBase . '/' . $this->modelName . '/getOne';
        $curl = $this->curl;
        $primaryKey = $this->primaryKey;
        $data = [
            $primaryKey => self::$info->$primaryKey,
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success', $curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }

    /**
     * @depends testGetOne
     * testUpdate
     * @author Tioncico
     * Time: 15:50
     */
    public function testUpdate()
    {
        $url = $this->apiBase . '/' . $this->modelName . '/update';
        $curl = $this->curl;
        $primaryKey = $this->primaryKey;
        $data = [$primaryKey => self::$info->$primaryKey] + $this->updateParam;
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success', $curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }


    /**
     * @depends testUpdate
     * testDelete
     * @author Tioncico
     * Time: 15:50
     */
    public function testDelete()
    {
        $url = $this->apiBase . '/' . $this->modelName . '/delete';
        $curl = $this->curl;
        $primaryKey = $this->primaryKey;
        $data = [
            $primaryKey => self::$info->$primaryKey,
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success', $curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }
}