<?php
/**
 * Created by PhpStorm.
 * User: Tioncico
 * Date: 2019/3/26 0026
 * Time: 17:45
 */

namespace Test\Admin;

use App\Model\Article\ArticleModel;
use App\Model\WebSettingModel;

class WebSettingTest extends AdminBaseTestCase
{
    /**
     * @var $info WebSettingModel
     */
    static $info;
    protected $modelName = 'WebSetting';
    protected $primaryKey = 'id';
    protected $addParam = [
        'name'  => 'web_name',
        'note'  => '测试',
        'value'  => '测试官网',
        'type'  => WebSettingModel::TYPE_TEXT,
    ];
    protected $updateParam = [
        'note'             => '测试2',
    ];

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * testAdd
     * @author Tioncico
     * Time: 16:03
     */
    public function testAdd()
    {
        $url = $this->apiBase . '/'.$this->modelName.'/add';
        $curl = $this->curl;
        $curl->get($url, $this->addParam);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success', $curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }

    /**
     * testGetAll
     * @author Tioncico
     * Time: 15:49
     */
    public function testGetAll()
    {
        $url = $this->apiBase . '/'.$this->modelName.'/getAll';
        $curl = $this->curl;
        $curl->get($url);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
        $this->assertGreaterThan(0, $curl->response->result->total);
        self::$info = new WebSettingModel((array) $curl->response->result->list[0]);
    }

    /**
     * testGetOne
     * @author Tioncico
     * Time: 15:50
     */
    public function testGetOne()
    {

        $url = $this->apiBase . '/'.$this->modelName.'/getOne';
        $curl = $this->curl;
        $primaryKey = $this->primaryKey;
        $data = [
            $primaryKey =>  self::$info->$primaryKey,
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }

    /**
     * @depends testGetOne
     * testUpdate
     * @throws \ErrorException
     * @author Tioncico
     * Time: 15:50
     */
    public function testUpdate()
    {
        $url = $this->apiBase . '/'.$this->modelName.'/update';
        $curl = $this->curl;
        $primaryKey = $this->primaryKey;
        $data = [$primaryKey =>  self::$info->$primaryKey] + $this->updateParam;
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }

    public function getList() {
        $model = new WebSettingModel();
        $primaryKey = $this->primaryKey;
        return $model->where([$primaryKey => self::$info->$primaryKey = $this->primaryKey])->all(null, true);
    }

    /**
     * @depends testUpdate
     * testDelete
     * @author Tioncico
     * Time: 15:50
     */
    public function testDelete()
    {
        $url = $this->apiBase . '/'.$this->modelName.'/delete';
        $curl = $this->curl;
        $primaryKey = $this->primaryKey;
        $data = [
            $primaryKey =>  self::$info->$primaryKey,
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $list = $this->getList();
        if (!empty($list)) {
            $this->assertEquals('该分类存在文章', $curl->response->msg);
            $this->assertEquals(400, $curl->response->code);
        } else {
            $this->assertEquals('success', $curl->response->msg);
            $this->assertEquals(200, $curl->response->code);
        }
    }
}
