<?php
/**
 * Created by PhpStorm.
 * User: Tioncico
 * Date: 2019/3/26 0026
 * Time: 17:45
 */

namespace Test\Common;

use App\Model\Article\ArticleCategoryBean;
use App\Model\Article\ArticleCategoryModel;
use App\Model\Article\ArticleModel;
use EasySwoole\MysqliPool\Mysql;
use EasySwoole\Utility\Str;

class ArticleCategoryTest extends CommonBaseTestCase
{
    /**
     * @var $info ArticleCategoryBean
     */
    static $info;
    protected $getPkMethod;
    protected $modelName = 'ArticleCategory';
    protected $primaryKey = 'categoryId';

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->getPkMethod = 'get' . Str::studly($this->primaryKey);
    }

    public function existArticleCategory() {

        $model = new ArticleCategoryModel();
        $list = $model->getAll();

        if (empty($list)) {
            $data = [
                'categoryName'  => 'ArticleCategory-Common测试',
                'pid'           => 0,
            ];
            $model = new ArticleCategoryModel($data);
            $ret = $model->save();
            $this->assertTrue(!!$ret);
        }

    }

    /**
     * testGetAll
     * @throws \ErrorException
     * @author Tioncico
     * Time: 15:49
     */
    public function testGetAll()
    {

        $this->existArticleCategory();

        $url = $this->apiBase . '/'.$this->modelName.'/getAll';
        $curl = $this->curl;
        $curl->get($url);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
        $this->assertGreaterThan(0, $curl->response->result->total);
        self::$info = new ArticleCategoryModel((array) $curl->response->result->list[0]);
    }

    /**
     * testGetOne
     * @throws \ErrorException
     * @author Tioncico
     * Time: 15:50
     */
    public function testGetOne()
    {

        $url = $this->apiBase . '/'.$this->modelName.'/getOne';
        $curl = $this->curl;
        $primaryKey = $this->primaryKey;
        $data = [
            $primaryKey =>  self::$info->$primaryKey,
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }

}
