<?php
/**
 * Created by PhpStorm.
 * User: Tioncico
 * Date: 2019/3/26 0026
 * Time: 17:45
 */

namespace Test\Common;

use App\Model\Article\ArticleBean;
use App\Model\Article\ArticleCategoryBean;
use App\Model\Article\ArticleCategoryModel;
use App\Model\Article\ArticleModel;
use EasySwoole\MysqliPool\Mysql;
use EasySwoole\Utility\Str;

class ArticleTest extends CommonBaseTestCase
{
    /**
     * @var $info ArticleModel
     */
    static $info;
    /**
     * @var $category ArticleCategoryModel
     */
    static $category;
    protected $getPkMethod;
    protected $modelName = 'Article';
    protected $primaryKey = 'articleId';

    protected $search = [
        'keyword'  => 'Article测试',
    ];

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->getPkMethod = 'get' . Str::studly($this->primaryKey);
    }

    function existArticleCategory() {
        $model = new ArticleCategoryModel();
        $info = $model->get();
        if (empty($info)) {
            $data = [
                'categoryName'  => '测试',
                'pid'           => 0,
            ];
            $model = new ArticleCategoryModel($data);
            $ret = $model->save();
            $this->assertTrue(!!$ret);
            self::$category = $model;
        } else {
            self::$category = $info;
        }
    }

    function existArticle() {
        $model = new ArticleModel();
        $list = $model->all();
        if (empty($list)) {
            $data = [
                'categoryId'            => self::$category->categoryId,
                'categoryName'          => self::$category->categoryName,
                'title'                 => 'Article-Common测试',
                'description'           => 'Article-Common测试',
                'author'                => 'blank',
                'content'               => 'Article-Common测试',
                'addTime'               => time(),
                'state'                 => 1,
            ];
            $bean = new ArticleBean($data);
            $ret = $model->add($bean);
            $this->assertTrue(!!$ret);
        }
    }

    /**
     * testGetAll
     * @throws \ErrorException
     * @author Tioncico
     * Time: 15:49
     */
    public function testGetAll()
    {
        $this->existArticleCategory();
        $this->existArticle();
        $url = $this->apiBase . '/'.$this->modelName.'/getAll';
        $curl = $this->curl;
        $curl->get($url);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
        $this->assertGreaterThan(0, $curl->response->result->total);
        self::$info = new ArticleModel((array) $curl->response->result->list[0]);
    }

    /**
     * @depends testGetAll
     * testGetOne
     * @throws \ErrorException
     * @author Tioncico
     * Time: 15:50
     */
    public function testGetOne()
    {
        $url = $this->apiBase . '/'.$this->modelName.'/getOne';
        $curl = $this->curl;
        $primaryKey = $this->primaryKey;
        $data = [
            $primaryKey =>  self::$info->$primaryKey,
        ];
        $curl->get($url, $data);
        if ($curl->response) {
//            var_dump($curl->response);
        } else {
            echo 'Error: ' . $curl->errorCode . ': ' . $curl->errorMessage . "\n";
        }
        $this->assertTrue(!!$curl->response);
        $this->assertEquals('success',$curl->response->msg);
        $this->assertEquals(200, $curl->response->code);
    }

}
