<?php
/**
 * Created by PhpStorm.
 * User: evalor
 * Date: 2019-03-26
 * Time: 19:17
 */

namespace Test\Common;

use Curl\Curl;
use Test\BaseTest;

/**
 * API测试基类
 * Class BaseApiTestCase
 * @package Test\ApiTest
 */
class CommonBaseTestCase extends BaseTest
{
    protected $apiBase = 'http://127.0.0.1:9602/Api/Common';
    protected $shopSession;
    protected $curl;
    protected $modelName = '';

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->curl = new Curl();
    }
}